id: A24CC94CC
title: Verses 21-40
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:04:43.267815
  last_modified_at: 2022-03-01 23:04:43.267821
